### ISSUE TITLE
aedi does not work with DMD v2.087.0

### ISSUE THREAD

**Issue by ghost91-** [aermicioi/aedi#14]
Trying to run the tests of aedi (or use it as a dependency) does not work when using DMD v2.087.0:
```
../../.dub/packages/aedi-1.0.0/aedi/source/aermicioi/aedi/container/proxy_container.d(217,36): Error: function `aermicioi.aedi.container.proxy_container.ProxyContainerImpl!(SingletonContainer).ProxyContainerImpl.remove` incompatible covariant types @safe Storage!(Factory!(Object), string)(string identity) and @safe Storage!(ProxyObjectFactory, string)(string identity)
../../.dub/packages/aedi-1.0.0/aedi/source/aermicioi/aedi/test/configurer/register/factory_configurer.d(196,21): Error: template instance `aermicioi.aedi.container.proxy_container.ProxyContainerImpl!(SingletonContainer)` error instantiating
```
